version: 2

models:
  - name: fact_rental
    description: "fact_rental"
    columns:
      - name: rental_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

models:
  - name: fact_payment
    description: "fact_payment"
    columns:
      - name: payment_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
