version: 2

models:

  - name: dim_staff
    description: "staff dimention model"
    columns:
      - name: staff_id
        description: "the primary key for this table"
        tests: 
          - unique
          - not_null 

  - name: dim_store
    description: "store dimention model"
    columns:
      - name: store_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  
  - name: dim_film
    description: "film dimention model"
    columns:
      - name: film_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_customer
    description: "customer dimention model"
    columns:
      - name: cusromer_id
        description: "the primary key for this table"
        tests: 
          - unique
          - not_null 

